// ── Translations ──────────────────────────────────────────────────────────────
const LANGS = {
  en: {
    myHand:'My Hand', opponent:'Opponent',
    duoRankings:'DUO — HAND RANKINGS & RULES',
    fiveRankings:'5-CARD HAND RANKINGS & RULES',
    fedoraGuideTab:'Fedora Guide',
    c1:'Card 1', c2:'Card 2', red:'Red', yellow:'Yellow',
    oppCard:'Opponent {n} — Visible Card',
    hiddenCard:'Opponent {n} — Hidden Card',
    fedoraOpponent:'Opponent {n} — Full Hand',
    promptCards:'Select your two cards to begin',
    promptOpp:"Select an opponent's card to calculate odds",
    promptOppFedora:'Select each opponent’s full Duo hand',
    winVs:'Win rate vs opponent', winVsAll:'Win rate vs all {n} opponents',
    situation:'Your Situation', first:'First Action', raise:'Facing a Raise',
    recAction:'Recommended Action',
    why:'Why',
    equity:'Effective equity', visibleInfo:'Visible info', threshold:'Threshold', note:'Note',
    f5VisibleNote:'Estimated from one visible opponent card',
    fedoraToggle:'Fedora',
    fedoraOn:'Fedora Active',
    fedoraOff:'Fedora Off',
    fullHandKnown:'Full hand known',
    handBehavior:'Hand Behavior', normalHand:'Normal hand', executorFallback:'Acts as 1 point unless its special case applies.', judgeFallback:'Acts as Zero unless the opponent hand is a Pair.', wardenFallback:'Rematch vs Un-Deux or below; otherwise vulnerable.', highWardenFallback:'Rematch vs Pair 8 or below. Pair 9 or higher is dangerous.',
    allin:'ALL-IN', dblRaise:'DOUBLE RAISE', halfRaise:'HALF RAISE', check:'CHECK', call:'CALL', fold:'FOLD',
    s_allin_f:'Dominant hand — maximise value immediately',
    s_dbl_f:'Clear edge — press your advantage with a full raise',
    s_half_f:'Slight edge — stay aggressive but measured',
    s_check:'Unfavourable — pass for free and see what develops',
    s_check_bluff:'Weak hand — let the timer run out and auto-check. The AI may read it as strength and fold (~40% of the time).',
    s_opp_danger:'Caution — opponent shows a dangerous card (1, 2, or 10). These enable strong named hands. Fold unless your hand is solid.',
    s_executor:'Executor is situational — it only beats Superior Pair. Against anything else it is worth 1 point. Consider folding unless you know the opponent holds Superior Pair.',
    s_allin_r:'Dominant hand — re-raise all-in and force folds',
    s_dbl_r:'Clear edge — re-raise and put pressure on opponents',
    s_half_r:'Slight edge — re-raise cautiously to control pot',
    s_call:'Behind but not hopeless — match and stay in',
    s_fold:'Too far behind — cut your losses now',
    allInBorderline:'Borderline — some risk remains',
    next:'Next Tour', reset:'Reset',
    win:'Win', tie:'Tie', lose:'Lose',
    vsOpp:'vs Opp {n}', showDtl:'Show Details', hideDtl:'Hide Details',
    addOpp:'+ Add', remOpp:'− Remove', foldBtn:'Fold', unfold:'Unfold',
    allFolded:'All opponents folded. You win!',
    rulesBtn:'Rules', close:'Close',
    sCol:'Special — Color Dependent', sAny:'Special — Any Color',
    sRank:'Ranked (strongest → weakest)',
    nUnbeat:'Unbeatable', nExec:'Beats Superior Pair', nRematch9:'Rematch ≤ 9-Pair', nSup:'Beats Sup. Pair',
    nAllStd:'Beats all except Sup. Pair', nPairs:'Beats all Pairs ≤9', nRematch2:'Rematch ≤ Un-Deux',
    nJudgeNote:'Treated as Zéro vs non-pairs', nExecNote:'Treated as 1pt vs non-Sup.',
    th2:'2nd Card', thHand:'Their Hand', thRes:'Result',
    thChance:'Chance',
    tkwHigh:'Kwang Card — High Threat', tkwDtl:'Can form {x}. Play defensively.',
    tr4High:'Red 4 — High Threat', tr4Dtl:'Enables High Warden, Executor, or Warden. Consider folding weak hands.',
    t10Med:'10 — Medium Threat', t10Dtl:'Can form Ten Pair. Be cautious with mid-range hands.',
    t1Med:'1 — Medium Threat', t1Dtl:'Can form One-two, One-four, One-nine, One-ten.',
    t9Med:'9 — Medium Threat', t9Dtl:'Can form Pair of 9s or Warden (4+9).',
    tLow:'Low Threat', tLowDtl:'Good opportunity to drag out the round.',
    selectMissing:'Select {x} to see your hand',
    selectYours:'Select your two cards',
    // Duo rules (for footer)
    duoRulesTitle:'Rules',
    duoAbout:'Played with 20 numbered cards (1–10), one red and one yellow of each. Form the strongest 2-card hand to win.',
    duoBets:'Betting Options',
    duoBet1:'Check — Pass without raising.',
    duoBet2:'All-In — Bet all your silver.',
    duoBet3:'Half Pot — Bet half the total pot.',
    duoBet4:'Raise — Double the previous bet.',
    duoBet5:'Call — Match the previous bet.',
    duoBet6:'Fold — Abandon the round.',
    duoExtra:'If you exceed 10 seconds, Call is auto-selected. Hands are revealed when all bets match or betting can no longer increase. If your silver drops below the buy-in, you cannot participate.',
    duoSpecialTitle:'Special Hand Rules',
    duoWarden:'Warden (4+9): Rematch if all players have a hand ≤ Un-Deux.',
    duoHWarden:'High Warden (R4+R9): Rematch if all players have a hand ≤ Pair of 9.',
    duoJudge:'Judge (3+7): Beats opponent if their best hand is a Pair (≤9). Otherwise treated as Zéro.',
    duoExecutor:'Executor (R4+R7): Beats Superior Pair. Cannot beat Prime Pair. Otherwise treated as 1 point.',
    // Five-Card specific
    f5hand:'My Hand (5-Card)', f5opp:'Opponent (5-Card)',
    f5prompt:'Select your 5 cards to begin',
    f5promptOpp:"Select an opponent's visible card",
    f5promptOppFedora:"Select each opponent's full 5-card hand",
    f5winVs:'Win rate vs opponent', f5winVsAll:'Win rate vs all {n} opponents',
    f5situation:'Your Situation',
    fedoraBase:'Base',
    fedoraFinal:'Final Hand',
    // 5-card rules sections
    r5about:'About Five-Card',
    r5about1:'Played with 40 sticks: two sets of 1–10, each in Red and Yellow. Red sticks are essential for the strongest hands.',
    r5about2:'The player who builds the strongest 2-card hand wins the pot.',
    r5how:'How to Play',
    r5how1:'Receive 5 sticks and combine 3 to total exactly 10, 20, or 30.',
    r5how2:'The best 2-card combination from the remaining sticks is your hand.',
    r5how3:'If no valid 3-stick total exists, your hand is a Bust — automatic loss.',
    r5bets:'Betting Options',
    r5b1:'Check — Pass without raising.',
    r5b2:'All-In — Bet all your silver.',
    r5b3:'Half — Bet half the total pot.',
    r5b4:'Raise — Double the previous bet.',
    r5b5:'Call — Match the previous bet.',
    r5b6:'Fold — Abandon the round.',
    r5tips:'Tips to Win',
    r5t1:'Wild Heart: Even a weak hand can win if you raise boldly — opponents may fold.',
    r5t2:'Strategic Fold: Cut your losses and prepare for the next round.',
    r5t3:'Sharp Eyes: Watch for cheating opponents and call them out.',
    // Spot Cheaters
    cheatTitle:'Spot Cheaters',
    cheatSubtitle:'How to catch them in the act',
    cheatIntro1:'',
    cheatWhenDealing:'When dealing the cards',
    cheatNormalLabel:'Normal',
    cheatNormalDesc:'They hold the bundle of cards with their <em>thumb pointing down</em> and deal naturally from the top.',
    cheatCheatLabel:'Cheating',
    cheatCheatDesc:'They grab the bundle from the side with their <em>thumb pointing up</em> to secretly pull a card from the bottom of the deck.',
    clickZoom:'Click to enlarge',
    cheatTip:'If you spot it, hold the <strong>Accuse</strong> button. Correct — they\'re removed and their silver is split between players. Wrong — you get temporarily banned from the gambling den for a couple of in-game days. Be sure before you accuse.',
    cheatWhenPlacing:'When placing the cards on the table',
    cheatPlaceNormalDesc:'They toss the cards onto the table with <em>confidence</em>, without hesitation.',
    cheatPlaceCheatDesc:'They bring both hands together and place the cards down very <em>carefully</em>, timidly.',
    fedoraGuideTitle:'Deceiver’s Fedora',
    fedoraGuideSubtitle:'How to unlock it and use it in Duo and Five-Card',
    fedoraGuideIntro:'It lets you see the full hands of your opponents in Duo and Five-Card games.',
    fedoraHowGet:'How to get it',
    fedoraStep1:'Go to this location in the Tashkalp region.',
    fedoraStep2:'Beat every opponent in the fighting pit and then defeat Muskan in the Emperor of the Bonepit quest chain.',
    fedoraStep3:'After beating Muskan, unlock the Mineral Shop. If it does not appear immediately, teleport to the next Nexus and return.',
    fedoraStep4:'Raise the vendor’s trust to 100%. Give Copper Pouches or repeatedly greet him between teleports.',
    fedoraStep5:'Once trust reaches 100%, buy the Deceiver’s Fedora.',
    fedoraHowUse:'How to use it',
    fedoraUse1:'After all cards are dealt, a new option appears at the bottom-right of the screen: Steal a Look at Hand.',
    fedoraUse2:'Press it to clearly reveal the full hands of your opponents.',
    fedoraLocationLabel:'Location',
    fedoraQuestLabel:'Quest Chain',
    fedoraBuyLabel:'Buy Fedora',
    fedoraUseLabel:'Use In Game',
  },
  fr: {
    myHand:'Ma Main', opponent:'Adversaire',
    duoRankings:'DUO — CLASSEMENT DES MAINS & RÈGLES',
    fiveRankings:'5-CARTES — MAINS & RÈGLES',
    fedoraGuideTab:'Guide Fedora',
    c1:'Carte 1', c2:'Carte 2', red:'Rouge', yellow:'Jaune',
    oppCard:'Adversaire {n} — Carte Visible',
    hiddenCard:'Adversaire {n} — Carte Cachée',
    fedoraOpponent:'Adversaire {n} — Main Complète',
    promptCards:'Sélectionnez vos cartes pour commencer',
    promptOpp:"Sélectionnez la carte d'un adversaire pour calculer",
    promptOppFedora:'Sélectionnez la main complète en Duo de chaque adversaire',
    winVs:'Taux de victoire vs adversaire', winVsAll:'Taux de victoire vs les {n} adversaires',
    situation:'Votre Situation', first:'Première Action', raise:'Face à une Relance',
    recAction:'Action Recommandée',
    why:'Pourquoi',
    equity:'Équité effective', visibleInfo:'Info visible', threshold:'Seuil', note:'Note',
    f5VisibleNote:'Estimé à partir d’une seule carte visible',
    fedoraToggle:'Fedora',
    fedoraOn:'Fedora Actif',
    fedoraOff:'Fedora Inactif',
    fullHandKnown:'Main complète connue',
    handBehavior:'Comportement de la main', normalHand:'Main normale', executorFallback:'Vaut 1 point sauf si son cas spécial s’applique.', judgeFallback:'Vaut Zéro sauf si la main adverse est une Paire.', wardenFallback:'Revanche contre Un-Deux ou moins ; sinon vulnérable.', highWardenFallback:'Revanche contre Paire 8 ou moins. Paire 9 ou plus est dangereuse.',
    allin:'TAPIS', dblRaise:'RELANCER', halfRaise:'RELANCE DE MOITIÉ', check:'PAROLE', call:'SUIVRE', fold:'SE COUCHER',
    s_allin_f:'Main dominante — maximiser la valeur immédiatement',
    s_dbl_f:'Avantage clair — appuyez avec une relance complète',
    s_half_f:'Léger avantage — restez agressif mais mesuré',
    s_check:'Cotes défavorables — passez gratuitement et observez',
    s_check_bluff:'Main faible — laissez le temps s\'écouler et cochez automatiquement. L\'IA peut interpréter cela comme une main forte et se coucher (~40% du temps).',
    s_opp_danger:'Attention — l\'adversaire montre une carte dangereuse (1, 2 ou 10). Celles-ci permettent des mains nommées puissantes. Couchez-vous sauf si votre main est solide.',
    s_executor:'L\'Exécuteur est situationnel — il ne bat que la Paire Supérieure. Sinon, il vaut 1 point. Envisagez de vous coucher, sauf si vous savez que l\'adversaire a une Paire Supérieure.',
    s_allin_r:'Main dominante — relancer tapis et forcer les couchers',
    s_dbl_r:'Avantage clair — relancer et mettre la pression',
    s_half_r:'Léger avantage — relancer prudemment pour le pot',
    s_call:'Derrière mais pas sans espoir — suivez à moindre coût',
    s_fold:'Trop en retard — coupez vos pertes maintenant',
    allInBorderline:'Limite — un risque subsiste',
    next:'Tour Suivant', reset:'Réinitialiser',
    win:'Victoire', tie:'Égalité', lose:'Défaite',
    vsOpp:'vs Adv {n}', showDtl:'Voir Détails', hideDtl:'Masquer',
    addOpp:'+ Ajouter', remOpp:'− Retirer', foldBtn:'Coucher', unfold:'Reprendre',
    allFolded:'Tous les adversaires se sont couchés. Vous gagnez !',
    rulesBtn:'Règles', close:'Fermer',
    sCol:'Spéciales — Couleur Obligatoire', sAny:'Spéciales — Toute Couleur',
    sRank:'Classées (plus forte → plus faible)',
    nUnbeat:'Imbattable', nExec:'Bat la Paire Supérieure', nRematch9:'Revanche ≤ Paire 9', nSup:'Bat Paire Sup.',
    nAllStd:'Bat tout sauf Paire Sup.', nPairs:'Bat toutes Paires ≤9', nRematch2:'Revanche ≤ Un-Deux',
    nJudgeNote:'Traité comme Zéro hors Paires', nExecNote:'Traité comme 1pt hors Paire Sup.',
    th2:'2e Carte', thHand:'Leur Main', thRes:'Résultat',
    thChance:'Chance',
    tkwHigh:'Carte Kwang — Menace Haute', tkwDtl:'Peut former {x}. Jouez défensivement.',
    tr4High:'Rouge 4 — Menace Haute', tr4Dtl:'Active Garde Haute, Exécuteur ou Garde.',
    t10Med:'10 — Menace Moyenne', t10Dtl:'Peut former une Paire de 10.',
    t1Med:'1 — Menace Moyenne', t1Dtl:'Peut former Un-deux, Un-quatre, Un-neuf, Un-dix.',
    t9Med:'9 — Menace Moyenne', t9Dtl:'Peut former Paire de 9 ou Garde (4+9).',
    tLow:'Menace Faible', tLowDtl:'Bonne opportunité pour prolonger le tour.',
    selectMissing:'Sélectionnez {x} pour voir votre main',
    selectYours:'Sélectionnez vos deux cartes',
    // Duo rules (for footer)
    duoRulesTitle:'Règles',
    duoAbout:'Joué avec 20 cartes numérotées (1–10), une rouge et une jaune de chaque. Formez la combinaison de 2 cartes la plus forte pour gagner.',
    duoBets:'Options de mise',
    duoBet1:'Parole — Passer sans augmenter la mise.',
    duoBet2:'Tapis — Miser l\'intégralité de ses pièces.',
    duoBet3:'Moitié du pot — Miser la moitié du pot total.',
    duoBet4:'Relancer — Miser le double de la mise précédente.',
    duoBet5:'Suivre — Miser la même somme que le précédent.',
    duoBet6:'Se coucher — Abandonner la manche en cours.',
    duoExtra:'Si vous dépassez 10 secondes, Suivre est sélectionné automatiquement. Les mains sont révélées quand toutes les mises sont égales ou que les enchères ne peuvent plus augmenter. Si vos pièces passent sous la mise de départ, vous ne pouvez plus participer.',
    duoSpecialTitle:'Règles des mains spéciales',
    duoWarden:'Garde (4+9) : Revanche si tous les joueurs ont une main ≤ Un-Deux.',
    duoHWarden:'Grand Gardien (R4+R9) : Revanche si tous les joueurs ont une main ≤ Paire de 9.',
    duoJudge:'Juge (3+7) : Bat l\'adversaire si sa meilleure main est une Paire (≤9). Sinon traité comme Zéro.',
    duoExecutor:'Exécuteur (R4+R7) : Bat la Paire Supérieure. Ne peut battre la Paire Suprême. Sinon traité comme 1 point.',
    // Five-Card specific
    f5hand:'Ma Main (Cinq-Cartes)', f5opp:'Adversaire (Cinq-Cartes)',
    f5prompt:'Sélectionnez vos 5 cartes pour commencer',
    f5promptOpp:"Sélectionnez la carte visible d'un adversaire",
    f5promptOppFedora:'Sélectionnez la main complète de 5 cartes de chaque adversaire',
    f5winVs:'Taux de victoire vs adversaire', f5winVsAll:'Taux de victoire vs les {n} adversaires',
    f5situation:'Votre Situation',
    fedoraBase:'Base',
    fedoraFinal:'Main finale',
    // 5-card rules sections
    r5about:'Le Cinq-Cartes',
    r5about1:'Joué avec 40 bâtons : deux séries de 1 à 10, en Rouge et Jaune. Les bâtons rouges sont essentiels pour les mains les plus fortes.',
    r5about2:'Le joueur qui forme la meilleure main de 2 cartes remporte le pot.',
    r5how:'Déroulement',
    r5how1:'Recevez 5 bâtons et combinez-en 3 pour obtenir exactement 10, 20 ou 30.',
    r5how2:'La meilleure combinaison des 2 bâtons restants constitue votre main.',
    r5how3:'Si aucun total valide n\'est possible, c\'est un Échec — défaite automatique.',
    r5bets:'Options de mise',
    r5b1:'Parole — Passer sans augmenter la mise.',
    r5b2:'Tapis — Miser l\'intégralité de ses pièces.',
    r5b3:'Moitié — Miser la moitié du pot.',
    r5b4:'Relancer — Miser le double de la mise précédente.',
    r5b5:'Suivre — Miser la même somme que le précédent.',
    r5b6:'Se coucher — Abandonner la manche.',
    r5tips:'Astuces pour gagner',
    r5t1:'Cœur de fauve : Même une main faible peut gagner si vous osez hausser la mise.',
    r5t2:'Reculer pour sauter : Coupez vos pertes et préparez la prochaine manche.',
    r5t3:'Yeux rapides : Surveillez les tricheurs et dénoncez-les.',
    // Spot Cheaters
    cheatTitle:'Démasquer les Tricheurs',
    cheatSubtitle:'Comment les prendre sur le fait',
    cheatIntro1:'',
    cheatWhenDealing:'Lors de la distribution',
    cheatNormalLabel:'Normal',
    cheatNormalDesc:'Ils tiennent le paquet avec le <em>pouce pointé vers le bas</em> et distribuent naturellement depuis le dessus.',
    cheatCheatLabel:'Triche',
    cheatCheatDesc:'Ils saisissent le paquet sur le côté avec le <em>pouce pointé vers le haut</em> pour tirer secrètement une carte depuis le dessous.',
    clickZoom:'Cliquer pour agrandir',
    cheatTip:'Si vous le surprenez, maintenez le bouton <strong>Démasquer</strong>. Correct — il est éliminé et ses pièces sont partagées. Faux — vous êtes temporairement banni du repaire pour quelques jours en jeu. Soyez sûr avant d\'accuser.',
    cheatWhenPlacing:'Lors du dépôt des cartes sur la table',
    cheatPlaceNormalDesc:'Ils lancent les cartes sur la table avec <em>assurance</em>, sans hésitation.',
    cheatPlaceCheatDesc:'Ils rapprochent les deux mains et posent les cartes très <em>délicatement</em>, de façon timide.',
    fedoraGuideTitle:'Fedora du Fourbe',
    fedoraGuideSubtitle:'Comment l’obtenir et l’utiliser en Duo et en Cinq-Cartes',
    fedoraGuideIntro:'Il vous permet de voir les mains complètes de vos adversaires dans les parties en Duo et en Cinq-Cartes.',
    fedoraHowGet:'Comment l’obtenir',
    fedoraStep1:'Rendez-vous à cet endroit dans la région de Tashkalp.',
    fedoraStep2:'Vainquez tous les adversaires de l’arène, puis Muskan dans la suite de quêtes de l’Empereur de la Fosse aux Os.',
    fedoraStep3:'Après avoir vaincu Muskan, débloquez la Boutique de Minéraux. Si elle n’apparaît pas tout de suite, téléportez-vous au Nexus suivant puis revenez.',
    fedoraStep4:'Montez la confiance du marchand à 100 %. Offrez-lui des bourses de cuivre ou saluez-le entre deux téléportations.',
    fedoraStep5:'Une fois la confiance à 100 %, achetez le Fedora du Fourbe.',
    fedoraHowUse:'Comment l’utiliser',
    fedoraUse1:'Une fois toutes les cartes distribuées, une nouvelle option apparaît en bas à droite de l’écran : Espionner la main adverse.',
    fedoraUse2:'Appuyez dessus pour révéler clairement la main complète de vos adversaires.',
    fedoraLocationLabel:'Emplacement',
    fedoraQuestLabel:'Suite de quêtes',
    fedoraBuyLabel:'Acheter le Fedora',
    fedoraUseLabel:'Utilisation',
  }
};

// ── Hand name tables ──────────────────────────────────────────────────────────
const HAND_NAMES = {
  en: {
    prime_pair:'Prime Pair', superior_pair:'Superior Pair', high_warden:'High Warden',
    executor:'Executor', ten_pair:'Ten Pair', warden:'Warden', judge:'Judge',
    one_two:'One-two', one_four:'One-four', one_nine:'One-nine', one_ten:'One-ten',
    four_ten:'Four-ten', four_six:'Four-six', perfect_nine:'Perfect Nine', zero:'Zero',
  },
  fr: {
    prime_pair:'Paire Primaire', superior_pair:'Paire Supérieure', high_warden:'Haute Garde',
    executor:'Exécuteur', ten_pair:'Paire de 10', warden:'Garde', judge:'Juge',
    one_two:'Un-deux', one_four:'Un-quatre', one_nine:'Un-neuf', one_ten:'Un-dix',
    four_ten:'Quatre-dix', four_six:'Quatre-six', perfect_nine:'Neuf Parfait', zero:'Zéro',
  }
};

// ── App state ─────────────────────────────────────────────────────────────────
const S = {
  c1: { n:null, col:null },
  c2: { n:null, col:null },
  opps: [{ n:null, col:null, n2:null, col2:null, folded:false }],
  dtl: {},
  raising: false,
  showRanks: false,
  fedora: false,
  media: null,
  lang: localStorage.getItem('duo5_lang') || 'en',
  mode: 'duo', // 'duo' | 'cinq' | 'cheat' | 'fedora'
};

// ── Five-Card state (5 card slots) ───────────────────────────────────────────
const S5 = {
  cards: [
    {n:null,col:null},{n:null,col:null},{n:null,col:null},
    {n:null,col:null},{n:null,col:null}
  ],
  opps: [{ cards: Array.from({length:5},()=>({n:null,col:null})), folded:false }],
  dtl: {},
  raising: false,
  showRanks5: false,
  fedora: false,
};

const makeDuoOpp = () => ({ n:null, col:null, n2:null, col2:null, folded:false });
const makeFiveOpp = () => ({ cards: Array.from({length:5},()=>({n:null,col:null})), folded:false });

// ── Game constants ────────────────────────────────────────────────────────────
const RK = { PP:100, SP:90, TP:80, PB:70, OT:60, OF:59, ON:58, OTn:57, FT:56, FS:55, P9:50, ZERO:0, NINE_PAIR:79 };
const TOP = ['prime_pair','superior_pair','ten_pair'];
const DECK = [];
for (let i=1;i<=10;i++) { DECK.push({n:i,col:'red'}); DECK.push({n:i,col:'yellow'}); }
const DECK5 = [];
for (let copy=0; copy<2; copy++) {
  for (let i=1;i<=10;i++) {
    DECK5.push({ id:`${copy}-r-${i}`, n:i, col:'red' });
    DECK5.push({ id:`${copy}-y-${i}`, n:i, col:'yellow' });
  }
}

// ── Hand evaluation ───────────────────────────────────────────────────────────
